# Generated by Django 5.1.6 on 2025-03-05 20:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LabIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lab_name",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="IP address of the lab's local server"
                    ),
                ),
                (
                    "sync_port",
                    models.PositiveIntegerField(
                        default=8000, help_text="Port for syncing data"
                    ),
                ),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="SyncLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                ("sync_time", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("SUCCESS", "Success"),
                            ("FAILED", "Failed"),
                            ("PARTIAL", "Partial Success"),
                        ],
                        max_length=20,
                    ),
                ),
                ("items_synced", models.PositiveIntegerField(default=0)),
                ("items_failed", models.PositiveIntegerField(default=0)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DataSyncQueue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "target_lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "sync_type",
                    models.CharField(
                        choices=[
                            ("USER", "User"),
                            ("EQUIPMENT", "Equipment"),
                            ("WORKSPACE", "Workspace"),
                            ("PROJECT", "Project"),
                            ("BOOKING", "Booking"),
                        ],
                        max_length=20,
                    ),
                ),
                ("item_id", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("PROCESSING", "Processing"),
                            ("COMPLETED", "Completed"),
                            ("FAILED", "Failed"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("data_payload", models.JSONField(help_text="JSON data to be synced")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("error_message", models.TextField(blank=True, null=True)),
            ],
            options={
                "unique_together": {("source_lab", "sync_type", "item_id")},
            },
        ),
        migrations.CreateModel(
            name="SharedResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("EQUIPMENT", "Equipment"),
                            ("WORKSPACE", "Workspace"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "resource_id",
                    models.PositiveIntegerField(
                        help_text="ID of the resource in its original lab"
                    ),
                ),
                ("resource_name", models.CharField(max_length=200)),
                (
                    "owner_lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "shared_with_lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "unique_together": {
                    ("resource_type", "resource_id", "owner_lab", "shared_with_lab")
                },
            },
        ),
    ]
