# Generated by Django 5.1.6 on 2025-03-05 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="EquipmentUsageLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("check_out_time", models.DateTimeField()),
                ("check_in_time", models.DateTimeField(blank=True, null=True)),
                ("purpose", models.TextField()),
                ("notes", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="MaintenanceRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("maintenance_date", models.DateField()),
                ("description", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Equipment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                ("serial_number", models.CharField(max_length=100, unique=True)),
                ("barcode", models.CharField(max_length=100, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("IN_USE", "In Use"),
                            ("MAINTENANCE", "Maintenance"),
                            ("SHARED", "Shared with another lab"),
                        ],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                (
                    "lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=100, null=True)),
                ("purchase_date", models.DateField(blank=True, null=True)),
                ("last_maintenance_date", models.DateField(blank=True, null=True)),
                ("next_maintenance_date", models.DateField(blank=True, null=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="equipment/"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment",
                        to="inventory.category",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "to_lab",
                    models.CharField(
                        choices=[
                            ("IVE", "IvE Design Studio"),
                            ("CEZERI", "Cezeri Lab"),
                            ("MEDTECH", "MedTech Lab"),
                        ],
                        max_length=20,
                    ),
                ),
                ("transfer_date", models.DateTimeField()),
                ("return_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transfers",
                        to="inventory.equipment",
                    ),
                ),
            ],
        ),
    ]
